# Generated by Django 6.0.2 on 2026-02-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_orderitem_review_cart_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cart',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('g', 'Gram')], max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product', 'size', 'weight')},
        ),
    ]
