# Generated by Django 6.0.2 on 2026-02-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cart_unique_together_cart_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
