# Generated by Django 6.0.2 on 2026-02-09 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cart_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product', 'price', 'size', 'weight', 'weight_unit')},
        ),
    ]
