# Generated by Django 4.2.7 on 2026-02-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_cart_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="lead_time",
            field=models.PositiveIntegerField(default=7),
        ),
    ]
