# Generated by Django 4.2.7 on 2026-02-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_complaint"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sales_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
