# Generated by Django 4.2.27 on 2026-03-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_browsinghistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="priority_level",
            field=models.CharField(
                choices=[("essential", "Essential"), ("optional", "Optional")],
                default="optional",
                max_length=20,
            ),
        ),
    ]
