# Generated by Django 4.2.27 on 2026-03-08 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_product_priority_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PACKED", "Order Packed"),
                            ("DISPATCHED", "Out for Delivery"),
                            ("NEARBY", "Nearby"),
                            ("DELIVERED", "Delivered"),
                        ],
                        default="PACKED",
                        max_length=20,
                    ),
                ),
                (
                    "traffic_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Traffic (1.0x)"),
                            ("MEDIUM", "Medium Traffic (1.5x)"),
                            ("HIGH", "Heavy Traffic (2.0x)"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                ("distance_km", models.FloatField(default=5.0)),
                ("predicted_eta", models.PositiveIntegerField(blank=True, null=True)),
                ("is_notified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("is_available", models.BooleanField(default=True)),
                ("current_lat", models.FloatField(default=12.9716)),
                ("current_lng", models.FloatField(default=77.5946)),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("location_name", models.CharField(blank=True, max_length=100)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_logs",
                        to="app.delivery",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliverySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("8 AM – 10 AM", "8 AM – 10 AM"),
                            ("10 AM – 12 PM", "10 AM – 12 PM"),
                            ("2 PM – 4 PM", "2 PM – 4 PM"),
                            ("6 PM – 8 PM", "6 PM – 8 PM"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("max_orders", models.PositiveIntegerField(default=10)),
                ("current_orders", models.PositiveIntegerField(default=0)),
            ],
            options={
                "unique_together": {("time_slot", "date")},
            },
        ),
        migrations.AddField(
            model_name="delivery",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.deliveryagent",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery",
                to="app.order",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.deliveryslot",
            ),
        ),
    ]
