# Generated by Django 4.2.27 on 2026-03-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryagent",
            name="vehicle_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
