# Generated by Django 4.2.27 on 2026-03-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_deliverypartnerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
