# Generated by Django 4.2.27 on 2026-03-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_order_commission_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="title",
            field=models.CharField(default="Complaint", max_length=200),
        ),
    ]
