# Generated by Django 4.2.27 on 2026-03-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_complaint_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="vendorprice",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="vendorprice",
            name="stock",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="vendorprice",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Percentage discount (e.g. 5 for 5%)",
                max_digits=5,
            ),
        ),
    ]
