# Generated by Django 4.2.27 on 2026-03-12 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_userpantry_pantryusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="shared_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_cart_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="reward_points",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SeasonalPack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="seasonal_packs/"
                    ),
                ),
                ("discount_percentage", models.FloatField(default=10.0)),
                ("is_active", models.BooleanField(default=True)),
                ("festival_name", models.CharField(blank=True, max_length=50)),
                ("products", models.ManyToManyField(to="app.product")),
            ],
        ),
        migrations.CreateModel(
            name="FamilyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=100)),
                ("group_code", models.CharField(max_length=10, unique=True)),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="family_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
