# Generated by Django 4.2.27 on 2026-03-28 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_cart_shared_by_customerprofile_reward_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.deliverypartnerprofile'),
        ),
    ]
